import logging
import torch
import argparse
import torchvision
import os.path as osp

from .utils.options_util import parse_options
from .utils.basicsr_util import make_exp_dirs, get_root_logger, get_time_str, dict2str
from .data import create_train_val_test_dataloader
from .models import build_model


def test_pipeline(root_path):
    # Command-line argument parsing setup.
    parser = argparse.ArgumentParser()
    parser.add_argument("-opt", type=str, required=True, help="Path or YAML String to option yml file.")
    parser.add_argument("--launcher", choices=['none', 'pytorch', 'slurm'], default='none', help='Job launcher.')
    parser.add_argument("--auto_resume", action="store_true", help="Resume a recently interrupted training session.")
    parser.add_argument("--debug", action="store_true", help="Enable debug mode.")
    parser.add_argument("--local_rank", type=int, default=0, help="Specify local rank.")
    parser.add_argument("--force_yml", nargs='+', default=None,
                        help="Force to update yml files. Examples: train:ema_decay=0.999.")

    # Parse options, set distributed setting, set random seed.
    opt, args = parse_options(parser=parser, root_path=root_path, is_train=False)
    opt['root_path'] = root_path

    # Configure pytorch's computing behavior on gpu.
    torch.backends.cudnn.benchmark = True
    # torch.backends.cudnn.deterministic = True

    # Mkdir for results.
    # make dirs: results(if function 'parse_options' parameter 'is_trian' is False),
    # depends on 'path' options in yaml generated by function 'parse_options'.
    make_exp_dirs(opt=opt)

    # Init logger, create results log file.
    # TODO: WARNING: should not use get_root_logger in the above codes, including the called functions.
    #  Otherwise the logger will not be properly initialized.
    log_file = osp.join(opt['path']['log'], f'testing_{opt["name"]}_{get_time_str()}.log')
    # log level(DEBUG, INFO, WARNING, ERROR, CRITICAL) gradually increase. logging.INFO record current level and above
    logger = get_root_logger(log_level=logging.INFO, log_file=log_file)
    logger.info(f'\n\tPyTorch: {torch.__version__}'
                f'\n\tTorchVision: {torchvision.__version__}')
    logger.info(dict2str(opt=opt))

    # Create test dataloaders.
    _, _, test_dataloaders, _, _ = create_train_val_test_dataloader(
        opt=opt, train=False, val=False, test=True)

    # Create model.
    model = build_model(opt=opt)

    # Start testing.
    logger.info(f'Start testing:')
    if opt.get('val') is not None:
        for test_dataloader in test_dataloaders:
            model.validation(dataloader=test_dataloader, current_iter=99999999, tb_logger=None,
                             save_img=opt['val'].get('save_img', True))
    else:
        raise ValueError('No val option were added')


if __name__ == "__main__":
    root_path = osp.normpath(osp.abspath(osp.join(__file__, osp.pardir, osp.pardir)))
    test_pipeline(root_path)
