import time
import torch
import logging
import datetime
import argparse
import torchvision
import os.path as osp
from collections import OrderedDict

from .utils.options_util import parse_options
from .utils.basicsr_util import (load_resume_state, make_exp_dirs, mkdir_and_rename,
                                 copy_opt_file, get_time_str, get_root_logger,
                                 dict2str, init_tb_loggers, MessageLogger, AvgTimer)
from .utils.data_util import CPUPrefetcher, CUDAPrefetcher
from .data import create_train_val_test_dataloader
from .models import build_model


def train_pipeline(root_path):
    # Command-line argument parsing setup.
    parser = argparse.ArgumentParser()
    parser.add_argument("-opt", type=str, required=True, help="Path or YAML String to option yml file.")
    parser.add_argument("--launcher", choices=['none', 'pytorch', 'slurm'], default='none', help='Job launcher.')
    parser.add_argument("--auto_resume", action="store_true", help="Resume a recently interrupted training session.")
    parser.add_argument("--debug", action="store_true", help="Enable debug mode.")
    parser.add_argument("--local_rank", type=int, default=0, help="Specify local rank.")
    parser.add_argument("--force_yml", nargs='+', default=None,
                        help="Force to update yml files. Examples: train:ema_decay=0.999.")

    # Load yaml options.
    opt, args = parse_options(parser=parser, root_path=root_path, is_train=True)
    opt['root_path'] = root_path

    # Configure pytorch's computing behavior on gpu.
    torch.backends.cudnn.benchmark = False  # Ensure computing performance.
    torch.backends.cudnn.deterministic = True  # Ensure consistency and repeatability of calculation results.

    # Load resume state.
    resume_state = load_resume_state(opt)

    # Make dirs for experiments and logger.
    if resume_state is None:
        # Make dirs: experients(if function 'parse_options' parameter 'is_trian' is True),
        # depends on 'path' options in yaml generated by function 'parse_options'.
        make_exp_dirs(opt=opt)
        # Make dirs: tb_logger
        if 'debug' not in opt['name'] and opt['logger'].get('use_tb_logger') and opt['rank'] == 0:
            tb_logger_dir = osp.join(opt['root_path'], 'tb_logger', opt['name'])
            mkdir_and_rename(path=tb_logger_dir)

    # Copy the yml file to the experiment root.
    copy_opt_file(opt_file=args.opt, experiments_root=opt['path']['experiments_root'])

    # Init logger, create experiments log file.
    # TODO: WARNING: should not use get_root_logger in the above codes, including the called functions.
    #  Otherwise the logger will not be properly initialized
    log_file = osp.join(opt['path']['log'], f'training_{opt["name"]}_{get_time_str()}.log')
    # log level(DEBUG, INFO, WARNING, ERROR, CRITICAL) gradually increase. logging.INFO record current level and above.
    logger = get_root_logger(log_level=logging.INFO, log_file=log_file)
    logger.info(f'\n\tPyTorch: {torch.__version__}'
                f'\n\tTorchVision: {torchvision.__version__}')
    logger.info(dict2str(opt=opt))

    # Initialize wandb logger and tensorboard logger.
    tb_logger = init_tb_loggers(opt=opt)

    # Create train dataloader and val dataloaders.
    train_dataloader, val_dataloaders, _, total_epochs, total_iters = create_train_val_test_dataloader(
        opt=opt, train=True, val=True, test=False)
    train_sampler = train_dataloader.sampler

    # Get train dataloader prefetcher.
    prefetch_mode = opt['datasets']['train'].get('prefetch_mode')
    if prefetch_mode is None or prefetch_mode == 'cpu':
        prefetcher = CPUPrefetcher(loader=train_dataloader)
    elif prefetch_mode == 'cuda':
        prefetcher = CUDAPrefetcher(loader=train_dataloader, opt=opt)
        logger.info(f'Use {prefetch_mode} prefetch dataloader')
        if opt['datasets']['train'].get('pin_memory') is not True:
            raise ValueError('Please set pin_memory=True for CUDAPrefetcher.')
    else:
        raise ValueError(f"Wrong prefetch_mode {prefetch_mode}. Supported ones are: None, 'cuda', 'cpu'.")

    # Create model.
    opt['current_iter'] = resume_state['iter'] if resume_state is not None else 0
    model = build_model(opt=opt)

    # If necessary, model resume training state.
    if resume_state is not None:
        model.resume_training(resume_state=resume_state)
        start_epoch, current_iter = resume_state['epoch'], resume_state['iter']
        logger.info(f'Resuming training from epoch: {start_epoch}, iter: {current_iter}')
    else:  # Resume_state is None
        start_epoch, current_iter = 1, 0

    # create message logger. (Formatted console outputs and add scalar information to tensorboard logger)
    msg_logger = MessageLogger(opt=opt, start_iter=current_iter, tb_logger=tb_logger,
                               total_epochs=total_epochs, total_iters=total_iters)

    # Start training.
    logger.info(f'Start training from epoch: {start_epoch}, iter: {current_iter}')
    data_timer, iter_timer = AvgTimer(), AvgTimer()  # Don't need to run .start function when initialization.
    start_time = time.time()
    # Iterate all epochs.
    for epoch in range(start_epoch, total_epochs + 1):
        train_sampler.set_epoch(epoch)  # Use epoch as random sample seed.
        prefetcher.reset()
        train_data = prefetcher.next()

        # Iterate over the batche of data in one epoch.
        while train_data is not None:
            data_timer.record()
            current_iter += 1
            if current_iter > total_iters:
                break

            # update learning rate
            model.update_learning_rate(current_iter=current_iter, warmup_iter=opt['train'].get('warmup_iter', -1))
            # model feed data
            model.feed_data(data=train_data)
            # optimize net_g (& net_d)
            model.optimize_parameters(current_iter=current_iter)

            iter_timer.record()

            if current_iter == 1:
                # Reset start time in msg_logger for more accurate eta_time. (Not work in resume mode.)
                msg_logger.reset_start_time()

            # Update log.
            if current_iter % opt['logger']['print_freq'] == 0 or current_iter == total_iters:
                log_vars = OrderedDict([('epoch', epoch),
                                        ('iter', current_iter),
                                        ('lrs', model.get_current_learning_rate()),
                                        ('time', iter_timer.get_avg_time()),
                                        ('data_time', data_timer.get_avg_time())])
                # Get model.log_dict which contains losses, metrics, and some other information.
                model_log_dict = model.get_current_log()  # Orderdict
                log_vars.update(model_log_dict)
                msg_logger(log_vars=log_vars)  # Call __call__ function in MessageLogger.

            # Save models and training states.
            if current_iter % opt['logger']['save_checkpoint_freq'] == 0:
                logger.info('Saving models and training states.')
                model.save(epoch=epoch, current_iter=current_iter)

            # Start validation.
            if opt.get('val') is not None and (current_iter % opt['val']['val_freq'] == 0):
                for val_dataloader in val_dataloaders:
                    model.validation(dataloader=val_dataloader, current_iter=current_iter, tb_logger=tb_logger,
                                     save_img=opt['val'].get('save_img', True))

            # Iterate over the next batch of data.
            data_timer.start(), iter_timer.start()
            train_data = prefetcher.next()

        # End while loop. (Iterate over the batche of data in one epoch.)
    # End for loop. (Iterate all epochs.)
    end_time = time.time()

    # Final.
    consumed_time = str(datetime.timedelta(seconds=(end_time - start_time)))
    logger.info(f'End of training. Time consumed: H:M:S.MS - {consumed_time}')
    logger.info('Save the latest model.')
    model.save(epoch=-1, current_iter=-1)  # -1 means last. If current_iter is -1, don't save the last training state.
    if opt.get('val') is not None:
        for val_dataloader in val_dataloaders:
            model.validation(dataloader=val_dataloader, current_iter=current_iter - 1, tb_logger=tb_logger,
                             save_img=opt['val'].get('save_img', True))
    if tb_logger is not None:
        tb_logger.close()


if __name__ == "__main__":
    root_path = osp.normpath(osp.abspath(osp.join(__file__, osp.pardir, osp.pardir)))
    train_pipeline(root_path)
