#-- general settings. --#
name: train_CDEHAT_MSE_SRx4_trained_on_CA2022S2NAIP
model_type: CDEHATModel
scale: 4
num_gpu: 1 # auto
manual_seed: 0


#-- dataset and dataloader setting. --#
datasets:
  # train dataset
  train:
    name: CA2022S2NAIP
    type: CA2022S2NAIPDataset
    dataroot_gt: datasets/CA-2022-S2-NAIP/CA-2022-S2-NAIP train/hr
    dataroot_lq: datasets/CA-2022-S2-NAIP/CA-2022-S2-NAIP train/lr
    suffix: [ .tif, .png, .jpg ]
    meta_info_file: datasets/CA-2022-S2-NAIP/train.txt
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: True
    use_rot: True

    # dataloader
    use_shuffer: True
    num_worker_per_gpu: 6
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  # val dataset
  val_1:
    name: CA2022S2NAIP
    type: CA2022S2NAIPDataset
    dataroot_gt: datasets/Test/ablation/CA-2022-S2-NAIP val/hr
    dataroot_lq: datasets/Test/ablation/CA-2022-S2-NAIP val/lr
    suffix: .tif
    meta_info_file: ~
    io_backend:
      type: disk


#-- network structures. --#
# generator.
network_g:
  type: CDEHAT
  img_size: 64
  patch_size: 1
  in_chans: 4
  out_chans: 4
  num_feat: 64
  embed_dim: 180
  depths: [ 4, 4, 4, 4, 4, 4 ]
  num_heads: [ 6, 6, 6, 6, 6, 6 ]
  window_size: 16
  mlp_ratio: 2
  use_checkpoint: False
  compress_ratio: 3
  squeeze_factor: 30
  conv_scale: 0.01
  overlap_ratio: 0.5
  upscale: 4
  resi_connection: 1conv
  downsampler: patchmerging
  upsampler: pixelshuffle
  mean: [ 0.4156, 0.3811, 0.3006, 0.6926 ] # For CA-2022-S2-NAIP dataset. Mean: [ 0.4156, 0.3811, 0.3006, 0.6926 ], std: [ 0.1096, 0.0883, 0.0947, 0.0930 ]


  cdp_feat: 4 # Number of CDP feature map channels, default value
  use_cdp: True
  encoder_iter: -1
  # WARNING!!!!
  # When training the first phase, this value("encoder_iter") should be set to the number of iterations
  # for the first phase. When the first phase is completed and the weights from the first phase are used
  # to train the second phase, this value should be set to -1.
  # e.g.: 123456 iters for first phase, -1 iters for second phase. Please determine based on the dataset training
  # epochs and number of iterations.



#-- paths. --#
path:
  resume_state: ~

  pretrain_network_g: ~
  param_key_g: params_ema
  strict_load_g: True


#-- training settings. --#
train:
  ema_decay: 0.999

  # optimizer.
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [ 0.9, 0.99 ]

  # scheduler.
  scheduler:
    type: MultiStepLR
    milestones: [ ]
    gamma: 0.5

  total_iter: 640000
  warmup_iter: -1  # No warm up.

  # losses.
  # l1 loss
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean


#-- validation settings. --#
val:
  val_freq: !!float 5e3
  save_img: True
  pbar: True
  tif: True

  # metrics.
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: True
      better: higher

    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: True
      better: higher


#-- logging settings. --#
logger:
  print_freq: !!float 2e1
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: True

  # weight & bais.
  wandb:
    project: ~
    resume_id: ~


#-- dist training settings. --#
dist_params:
  backend: nccl
  port: 29500


